export const SHORTLIST_KEY = 'careerops_shortlist_v1';
export const SETUP_DISMISS_KEY = 'careerops_setup_dismiss';

export const state = {
  applications: [],
  metrics: null,
  path: '',
  states: [],
  filter: 'all',
  q: '',
  sort: { key: 'num', dir: 'desc' },
  portalsConfig: null,
  positive: [],
  negative: [],
  companies: [],
  focusPresets: null,
  cvText: '',
  lastJobs: [],
  inboxItems: [],
  runbookLoaded: false,
  runbookCommands: [],
  weather: null,
  comparePick: new Set(),
  interviewItems: [],
  interviewTab: 'story',
  interviewCurrent: 'story-bank.md',
  focus: {
    active: false,
    remaining: 0,
    total: 0,
    intervalId: null,
    paused: false,
  },
  rehearsal: {
    pack: null,
    roundSec: 90,
    roundLeft: 90,
    roundTimerId: null,
  },
  livePractice: {
    active: false,
    pack: null,
    mode: 'ledger',
    qIndex: 0,
    roundSec: 90,
    roundLeft: 90,
    roundTimerId: null,
  },
  session: { cloud: false, user: null },
  discoverRolesList: [],
  applyJumpNum: null,
  applyAutoLoad: false,
  applyPack: null,
  outreachJumpNum: null,
  outreachAutoLoad: false,
  outreachPack: null,
};

